//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoslynCodeTaskFactory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoslynCodeTaskFactory.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3420: The &quot;{0}&quot; attribute of the &lt;{1}&gt; element has been set but is empty. If the &quot;{0}&quot; attribute is set it must not be empty..
        /// </summary>
        internal static string CodeTaskFactory_AttributeEmpty {
            get {
                return ResourceManager.GetString("CodeTaskFactory_AttributeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3421: The &lt;Code&gt; element is missing for the &quot;{0}&quot; task. This element is required..
        /// </summary>
        internal static string CodeTaskFactory_CodeElementIsMissing {
            get {
                return ResourceManager.GetString("CodeTaskFactory_CodeElementIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling task source code.
        /// </summary>
        internal static string CodeTaskFactory_CompilingAssembly {
            get {
                return ResourceManager.GetString("CodeTaskFactory_CompilingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3429: Could not find assembly reference &quot;{0}&quot;..
        /// </summary>
        internal static string CodeTaskFactory_CouldNotFindReferenceAssembly {
            get {
                return ResourceManager.GetString("CodeTaskFactory_CouldNotFindReferenceAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source file for this compilation can be found at: &quot;{0}&quot;.
        /// </summary>
        internal static string CodeTaskFactory_FindSourceFileAt {
            get {
                return ResourceManager.GetString("CodeTaskFactory_FindSourceFileAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3423: The specified code language &quot;{0}&quot; is invalid.  The supported code languages are &quot;{1}&quot;..
        /// </summary>
        internal static string CodeTaskFactory_InvalidCodeLanguage {
            get {
                return ResourceManager.GetString("CodeTaskFactory_InvalidCodeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3424: The specified code type &quot;{0}&quot; is invalid.  The supported code types are &quot;{1}&quot;..
        /// </summary>
        internal static string CodeTaskFactory_InvalidCodeType {
            get {
                return ResourceManager.GetString("CodeTaskFactory_InvalidCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3425: The element &lt;{0}&gt; is not a valid child of the &lt;{1}&gt; element.{2}.
        /// </summary>
        internal static string CodeTaskFactory_InvalidElementLocation {
            get {
                return ResourceManager.GetString("CodeTaskFactory_InvalidElementLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3426: The specified task XML is invalid.  {0}.
        /// </summary>
        internal static string CodeTaskFactory_InvalidTaskXml {
            get {
                return ResourceManager.GetString("CodeTaskFactory_InvalidTaskXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3427: Only one &lt;Code&gt; element can be specified..
        /// </summary>
        internal static string CodeTaskFactory_MultipleCodeNodes {
            get {
                return ResourceManager.GetString("CodeTaskFactory_MultipleCodeNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB3428: You must specify source code within the Code element or a path to a file containing source code..
        /// </summary>
        internal static string CodeTaskFactory_NoSourceCode {
            get {
                return ResourceManager.GetString("CodeTaskFactory_NoSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for debugger to attach ({0} PID {1}).  Press enter to continue....
        /// </summary>
        internal static string CodeTaskFactory_WaitingForDebugger {
            get {
                return ResourceManager.GetString("CodeTaskFactory_WaitingForDebugger", resourceCulture);
            }
        }
    }
}
